### ISSUE TITLE
Unlocated Feature

### ISSUE THREAD

**Issue by VladimirKalachikhin** [perliedman/leaflet-realtime#86] opened 2017-09-28 18:49 UTC
If L.realtime source return something as:
{"type":"Feature","geometry":null,"properties":{"id":"gpsd","status":"noGPSD"}}
that is "geometry":null 
then UpdateEvent property "features" is {} instead of 
{"gpsd":{"type":"Feature","geometry":null,"properties":{"id":"gpsd","status":"noGPSD"}}}

**Comment by VladimirKalachikhin** [comment] 2018-03-16 19:23
Any features without "geometry" are not included into UpdateEvent property "features".

**Comment by perliedman** [comment] 2019-09-07 10:38
Hi, sorry for a late reply. I looked into implementing this, but decided this is too much of an edge case to be worth it: it would require some quite intricate restructuring of the code, which I am not up to, especially given the risk of introducing regressions while doing so.

I am closing this as a "will not fix", but since it _is_ valid GeoJSON, I am open to a PR to address this if this is an important feature to you. Just make sure to test thoroughly!

**Closed by perliedman** 2019-09-07 10:38 UTC
