### ISSUE TITLE
Only showing a single marker

### ISSUE THREAD

**Issue by spydmobile** [perliedman/leaflet-realtime#77] opened 2017-06-28 00:15 UTC
Hi, any idea why leaflet-realtime is only rendering the first point in my data?

`{"type":"FeatureCollection","totalFeatures":41,"features":[{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3df7","geometry":{"type":"Point","coordinates":[-120.134333,62.081833]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"FS010-17","size":"1.8000","status":"OC","response":"Being Monitored","causedby":"Natural","startdate":"2017-06-27T11:15:00","outdate":"","fireageday":0,"latlon":"POINT(-120.134333 62.081833)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3df8","geometry":{"type":"Point","coordinates":[-114.070833,62.510833]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"ZF006-17","size":"0.1000","status":"DO","response":"Initial Attack","causedby":"Person Caused","startdate":"2017-06-26T16:51:05.557","outdate":"2017-06-26T18:30:00","fireageday":1,"latlon":"POINT(-114.070833 62.510833)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3df9","geometry":{"type":"Point","coordinates":[-114.386833,62.456666]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"ZF005-17","size":"0.2000","status":"DO","response":"Initial Attack","causedby":"Person Caused","startdate":"2017-06-25T14:30:00","outdate":"2017-06-26T11:15:00","fireageday":2,"latlon":"POINT(-114.386833 62.456666)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3dfa","geometry":{"type":"Point","coordinates":[-125.792166,65.2895]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"VQ012-17","size":"0.4000","status":"UC","response":"Initial Attack","causedby":"Natural","startdate":"2017-06-25T19:00:00","outdate":"","fireageday":2,"latlon":"POINT(-125.792166 65.2895)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3dfb","geometry":{"type":"Point","coordinates":[-113.483333,62.5]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"ZF004-17","size":"2.0000","status":"DO","response":"Initial Attack","causedby":"Person Caused","startdate":"2017-06-24T16:24:00.767","outdate":"2017-06-26T14:52:00","fireageday":3,"latlon":"POINT(-113.483333 62.5)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3dfc","geometry":{"type":"Point","coordinates":[-130.257666,65.742833]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"VQ011-17","size":"0.5000","status":"OC","response":"Being Monitored","causedby":"Natural","startdate":"2017-06-24T17:05:00","outdate":"","fireageday":3,"latlon":"POINT(-130.257666 65.742833)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3dfd","geometry":{"type":"Point","coordinates":[-129.730166,65.654]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"VQ009-17","size":"163.0000","status":"OC","response":"Being Monitored","causedby":"Natural","startdate":"2017-06-23T17:00:00","outdate":"","fireageday":4,"latlon":"POINT(-129.730166 65.654)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3dfe","geometry":{"type":"Point","coordinates":[-114.2705,62.376333]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"ZF003-17","size":"0.2000","status":"DO","response":"Initial Attack","causedby":"Person Caused","startdate":"2017-06-23T17:30:00","outdate":"2017-06-24T12:50:00","fireageday":4,"latlon":"POINT(-114.2705 62.376333)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3dff","geometry":{"type":"Point","coordinates":[-129.439166,65.496666]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"VQ010-17","size":"154.0000","status":"OC","response":"Being Monitored","causedby":"Natural","startdate":"2017-06-23T17:10:00","outdate":"","fireageday":4,"latlon":"POINT(-129.439166 65.496666)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e00","geometry":{"type":"Point","coordinates":[-131.953666,66.182]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"EV006-17","size":"513.0800","status":"OC","response":"Being Monitored","causedby":"Natural","startdate":"2017-06-22T15:30:00","outdate":"","fireageday":5,"latlon":"POINT(-131.953666 66.182)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e01","geometry":{"type":"Point","coordinates":[-127.6105,65.5995]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"VQ007-17","size":"350.0000","status":"OC","response":"Being Monitored","causedby":"Natural","startdate":"2017-06-22T12:37:00","outdate":"","fireageday":5,"latlon":"POINT(-127.6105 65.5995)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e02","geometry":{"type":"Point","coordinates":[-120.905666,61.926166]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"FS009-17","size":"108.7500","status":"OC","response":"Abandoned","causedby":"Natural","startdate":"2017-06-22T17:22:00","outdate":"","fireageday":5,"latlon":"POINT(-120.905666 61.926166)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e03","geometry":{"type":"Point","coordinates":[-125.15,65.15]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"VQ006-17","size":"5.0000","status":"OC","response":"Abandoned","causedby":"Natural","startdate":"2017-06-21T18:05:00","outdate":"","fireageday":6,"latlon":"POINT(-125.15 65.15)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e04","geometry":{"type":"Point","coordinates":[-114.602166,62.348]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"ZF002-17","size":"0.0100","status":"DO","response":"Initial Attack","causedby":"Person Caused","startdate":"2017-06-21T20:12:10.437","outdate":"2017-06-22T10:00:00","fireageday":6,"latlon":"POINT(-114.602166 62.348)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e05","geometry":{"type":"Point","coordinates":[-127.670833,65.599666]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"VQ005-17","size":"4.0000","status":"OC","response":"Being Monitored","causedby":"Natural","startdate":"2017-06-20T17:30:00","outdate":"","fireageday":7,"latlon":"POINT(-127.670833 65.599666)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e06","geometry":{"type":"Point","coordinates":[-130.878666,66.304833]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"VQ008-17","size":"890.0000","status":"OC","response":"Being Monitored","causedby":"Natural","startdate":"2017-06-20T09:10:00","outdate":"","fireageday":7,"latlon":"POINT(-130.878666 66.304833)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e07","geometry":{"type":"Point","coordinates":[-110.9645,60.0965]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"SS007-17","size":"2.0000","status":"DO","response":"Sustained Action","causedby":"Natural","startdate":"2017-06-19T17:38:06.953","outdate":"2017-06-21T14:00:00","fireageday":8,"latlon":"POINT(-110.9645 60.0965)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e08","geometry":{"type":"Point","coordinates":[-136.079,67.057833]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"EV005-17","size":"112.0000","status":"DO","response":"Being Monitored","causedby":"Natural","startdate":"2017-06-19T17:00:00","outdate":"2017-06-22T14:25:00","fireageday":8,"latlon":"POINT(-136.079 67.057833)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e09","geometry":{"type":"Point","coordinates":[-127.5075,65.758166]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"VQ004-17","size":"0.0100","status":"DO","response":"Being Monitored","causedby":"Natural","startdate":"2017-06-18T17:57:07.397","outdate":"2017-06-20T15:33:00","fireageday":9,"latlon":"POINT(-127.5075 65.758166)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e0a","geometry":{"type":"Point","coordinates":[-134.623333,67.433333]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"EV004-17","size":"3.0000","status":"DO","response":"Sustained Action","causedby":"Natural","startdate":"2017-06-18T21:56:37.853","outdate":"2017-06-20T18:08:00","fireageday":9,"latlon":"POINT(-134.623333 67.433333)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e0b","geometry":{"type":"Point","coordinates":[-133.701,67.318333]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"EV003-17","size":"5.9000","status":"DO","response":"Sustained Action","causedby":"Person Caused","startdate":"2017-06-15T19:48:10.927","outdate":"2017-06-19T13:11:00","fireageday":12,"latlon":"POINT(-133.701 67.318333)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e0c","geometry":{"type":"Point","coordinates":[-125.396,64.898]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"VQ003-17","size":"1.0000","status":"UC","response":"Initial Attack","causedby":"Natural","startdate":"2017-06-15T20:00:00","outdate":"","fireageday":12,"latlon":"POINT(-125.396 64.898)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e0d","geometry":{"type":"Point","coordinates":[-134.846833,67.372833]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"EV002-17","size":"0.5000","status":"DO","response":"Initial Attack","causedby":"Person Caused","startdate":"2017-06-08T19:00:00","outdate":"2017-06-08T20:00:00","fireageday":19,"latlon":"POINT(-134.846833 67.372833)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e0e","geometry":{"type":"Point","coordinates":[-121.015,61.740833]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"FS008-17","size":"5.0000","status":"DO","response":"Sustained Action","causedby":"Natural","startdate":"2017-06-07T14:05:00","outdate":"2017-06-12T11:30:00","fireageday":20,"latlon":"POINT(-121.015 61.740833)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e0f","geometry":{"type":"Point","coordinates":[-112.475,61.4935]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"SS006-17","size":"0.2000","status":"OC","response":"Being Monitored","causedby":"Natural","startdate":"2017-05-31T11:35:00","outdate":"","fireageday":27,"latlon":"POINT(-112.475 61.4935)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e10","geometry":{"type":"Point","coordinates":[-119.083333,61.966666]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"FS007-17","size":"0.0100","status":"DO","response":"Being Monitored","causedby":"Natural","startdate":"2017-05-31T16:24:00","outdate":"2017-06-22T11:28:00","fireageday":27,"latlon":"POINT(-119.083333 61.966666)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e11","geometry":{"type":"Point","coordinates":[-122.6,62.083333]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"FS006-17","size":"0.0100","status":"OC","response":"Being Monitored","causedby":"Natural","startdate":"2017-05-31T14:09:00","outdate":"","fireageday":27,"latlon":"POINT(-122.6 62.083333)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e12","geometry":{"type":"Point","coordinates":[-120.55,61.183333]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"FS004-17","size":"1.0000","status":"DO","response":"Initial Attack","causedby":"Natural","startdate":"2017-05-30T18:03:04.503","outdate":"2017-06-04T11:22:00","fireageday":28,"latlon":"POINT(-120.55 61.183333)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e13","geometry":{"type":"Point","coordinates":[-117.833333,60.216666]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"SS004-17","size":"1.0000","status":"DO","response":"Delayed Action","causedby":"Natural","startdate":"2017-05-30T18:32:49.517","outdate":"2017-06-04T11:20:00","fireageday":28,"latlon":"POINT(-117.833333 60.216666)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e14","geometry":{"type":"Point","coordinates":[-122.733333,60.9]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"FS005-17","size":"2.0000","status":"DO","response":"Sustained Action","causedby":"Natural","startdate":"2017-05-30T20:05:00","outdate":"2017-06-03T14:30:00","fireageday":28,"latlon":"POINT(-122.733333 60.9)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e15","geometry":{"type":"Point","coordinates":[-120.55,61.416666]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"FS003-17","size":"17.0000","status":"DO","response":"Sustained Action","causedby":"Natural","startdate":"2017-05-30T17:57:00","outdate":"2017-06-03T16:30:00","fireageday":28,"latlon":"POINT(-120.55 61.416666)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e16","geometry":{"type":"Point","coordinates":[-117.283333,60.25]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"SS005-17","size":"26.9000","status":"DO","response":"Being Monitored","causedby":"Natural","startdate":"2017-05-30T18:44:18.033","outdate":"2017-06-04T11:34:00","fireageday":28,"latlon":"POINT(-117.283333 60.25)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e17","geometry":{"type":"Point","coordinates":[-117.159333,60.280833]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"SS003-17","size":"716.0000","status":"DO","response":"Being Monitored","causedby":"Natural","startdate":"2017-05-30T17:56:47.99","outdate":"2017-06-04T11:00:00","fireageday":28,"latlon":"POINT(-117.159333 60.280833)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e18","geometry":{"type":"Point","coordinates":[-121.368333,60.606666]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"FS002-17","size":"3.0000","status":"DO","response":"Sustained Action","causedby":"Natural","startdate":"2017-05-30T15:51:00","outdate":"2017-06-03T18:00:00","fireageday":28,"latlon":"POINT(-121.368333 60.606666)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e19","geometry":{"type":"Point","coordinates":[-122.4,60.166666]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"FS001-17","size":"67.5000","status":"DO","response":"Delayed Action","causedby":"Natural","startdate":"2017-05-29T15:58:00","outdate":"2017-06-07T16:00:00","fireageday":29,"latlon":"POINT(-122.4 60.166666)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e1a","geometry":{"type":"Point","coordinates":[-128.619666,66.258333]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"VQ002-17","size":"0.1000","status":"DO","response":"Limited Action","causedby":"Person Caused","startdate":"2017-05-25T23:50:00","outdate":"2017-05-25T23:56:00","fireageday":33,"latlon":"POINT(-128.619666 66.258333)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e1b","geometry":{"type":"Point","coordinates":[-128.624166,66.258333]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"VQ001-17","size":"0.1000","status":"DO","response":"Limited Action","causedby":"Person Caused","startdate":"2017-05-25T23:45:00","outdate":"2017-06-06T11:57:00","fireageday":33,"latlon":"POINT(-128.624166 66.258333)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e1c","geometry":{"type":"Point","coordinates":[-114.8465,62.464666]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"ZF001-17","size":"0.2000","status":"DO","response":"Sustained Action","causedby":"Natural","startdate":"2017-05-24T14:25:41.367","outdate":"2017-05-30T17:35:00","fireageday":34,"latlon":"POINT(-114.8465 62.464666)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e1d","geometry":{"type":"Point","coordinates":[-112.25,60.116666]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"SS002-17","size":"0.0100","status":"DO","response":"Initial Attack","causedby":"Person Caused","startdate":"2017-05-24T14:00:00","outdate":"2017-05-25T11:00:00","fireageday":34,"latlon":"POINT(-112.25 60.116666)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e1e","geometry":{"type":"Point","coordinates":[-115.814833,60.754333]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"SS001-17","size":"0.2000","status":"DO","response":"Initial Attack","causedby":"Person Caused","startdate":"2017-05-21T11:44:05.41","outdate":"2017-05-24T15:00:00","fireageday":37,"latlon":"POINT(-115.814833 60.754333)"}},{"type":"Feature","id":"firesit_public.fid--1264dfa_15cec086321_3e1f","geometry":{"type":"Point","coordinates":[-134.888833,67.4375]},"geometry_name":"the_geom","properties":{"year":"2017","fireid":"EV001-17","size":"1.0000","status":"DO","response":"Initial Attack","causedby":"Person Caused","startdate":"2017-05-17T11:35:00","outdate":"2017-05-18T15:41:00","fireageday":41,"latlon":"POINT(-134.888833 67.4375)"}}],"crs":{"type":"name","properties":{"name":"urn:ogc:def:crs:EPSG::4326"}}}`

**Comment by perliedman** [comment] 2017-06-28 06:18
Hi, this looks like a duplicate of #58, you need to tell Leaflet Realtime how to uniquely identify the features.

Please see the second paragraph of the [overview](https://github.com/perliedman/leaflet-realtime#overview), and use the `getFeatureId` option (see [docs for `L.Realtime`](https://github.com/perliedman/leaflet-realtime#lrealtime)

**Closed by perliedman** 2017-06-28 06:18 UTC

**Comment by spydmobile** [comment] 2017-06-28 13:38
Ahh thanks!
