### ISSUE TITLE
_bustCache function incorrectly applying query string

### ISSUE THREAD

**Issue by JGFalkirk** [perliedman/leaflet-realtime#144] opened 2019-08-05 09:59 UTC
`_bustCache` is adding the `_` parameter to the GeoJSON source URL by assuming that the URL does not use any query string already. This causes any source urls using query strings to not function as intended as the query parameters are technically invalid.

**Example:**

Source URL when initialising Realtime is set to `http://example.com/vehicles.ashx?type=Car` causes requests to be made for URLs like `http://example.com/vehicles.ashx?type=Car?_=123456789`

The correct URL should be `http://example.com/vehicles.ashx?type=Car&_=123456789`

**Comment by perliedman** [comment] 2019-09-07 10:57
Hi!

I can't reproduce this, and there is code in place to handle this (https://github.com/perliedman/leaflet-realtime/blob/master/src/L.Realtime.js#L284). You can for example change the URL in the example to something like `https://wanderdrone.appspot.com/?foo=bar`, and the URL is built correctly using `&` as separator between the `foo` and `_` parameters.

Closing, but will re-open if you provide steps to reproduce.

**Closed by perliedman** 2019-09-07 10:57 UTC
