### ISSUE TITLE
Change marker icon, when update json properties.

### ISSUE THREAD

**Issue by EvgenPhm** [perliedman/leaflet-realtime#34] opened 2016-06-04 03:52 UTC
Hello, i am sorry but i don't need update my coordinates, i want use it for update my markers icons depend on value of any property.
For example my json is:

{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates":
                    [87.95235,52.9535]

            },
            "properties": {
                "name": "MK Lift queues",
                "Qtype": "3",
                "id": "101"
            }

        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates":
                    [87.94178,52.96022]

            },
            "properties": {
                "name": "Dollar Lift Queues",
                "Qtype": "1",
                "id": "102"
            }

        }

    ]
}

And my part of code index.js is:
var realtime = L.realtime({
                            url:'queues.geojson',
                            crossOrigin: true,
                            type: 'json'},
                                {interval: 3000,

//                                onEachFeature: onEachFeature,
                                pointToLayer: function (feature, latlng) {
                                    if (feature.properties.Qtype == "4"){
                                        return L.marker(latlng, {icon: LiftQ4Icon});
                                    }
                                    if (feature.properties.Qtype == "3"){
                                        return L.marker(latlng, {icon: LiftQ3Icon});
                                    }
                                    if (feature.properties.Qtype == "2"){
                                        return L.marker(latlng, {icon: LiftQ2Icon});
                                    }
                                    if (feature.properties.Qtype == "1"){
                                        return L.marker(latlng, {icon: LiftQ1Icon});
                                    }
                                }

                                }
                        ).addTo(liftsgroup);

So it updates markers only when i reload the page, but i wand to update markers, when i change property "Qtype". Help me please, and sorry for my bad english.

**Comment by perliedman** [comment] 2016-06-04 11:57
This is mostly a duplicate of #3, and there's currently not built-in way to solve this.

However, you should be able to fix this using the [`updateFeature` option](https://github.com/perliedman/leaflet-realtime#-options), with something like this:

```javascript
var realtime = new L.Realtime(..., {
    updateFeature: function(feature, oldLayer, newLayer) {
        oldLayer.setIcon(newLayer._icon);
        return L.Realtime.prototype.options.updateFeature(feature, oldLayer, newLayer);
    }
}
```

**Closed by perliedman** 2016-06-04 11:57 UTC
