### ISSUE TITLE
URL not called

### ISSUE THREAD

**Issue by sfindlay** [perliedman/leaflet-realtime#92] opened 2017-11-22 00:53 UTC
I have a $.getJSON with L.getJSON I'm trying to conver to realtime however the url specified never fires. Not sure what the issue is I have simplified the code as much as possible with no luck. Any ideas?

**Comment by perliedman** [comment] 2017-11-22 08:14
Hi,
it's really hard for me to tell without seeing some code, unfortunately. Also, make sure you don't have any error messages in devtools, if you haven't already.

**Comment by sfindlay** [comment] 2017-11-22 16:03
Thanks for the email! I have been looking for errors as you can see bellow, also please note the alert Running: running is displayed which I think would indicate that it is working. I have used the URL with $.getJSO and L.geoJSON successfully so I don’t think it is the webservice…


try {
    realtimeLayer = L.realtime({
        url: 'http://localhost:8080/cityReporter/Mapping/devicePositionsFiltered?startDate=1511311078410&endDate=1511325478410&areaid=-1',
        crossOrigin: true,
        type: 'json'
    }, {
        start: 'True',
        interval: 20000
    }).addTo(map);
}
catch (err) {
    alert('Error: '||err.message)
}

realtimeLayer.on('update', function() {
    alert('On Realtime');
    map.fitBounds(realtimeLayer.getBounds(), {maxZoom: 3});
});

if (realtimeLayer.isRunning())
    alert('Running: running');
else
    alert('Running: not running');


Steven Findlay

CEO
Noratek Solutions, Inc
Work:  (250) 564-2236 | Cell:  (250) 981-3025
sfindlay@noratek.com<mailto:sfindlay@noratek.com>
http://www.noratek.com/ | https://www.cityinspectionsoftware.com<https://www.cityinspectionsoftware.com/>

Noratek Solutions 200-1840 3rd Avenue Prince George, BC V2M 1G4 Canada

**Comment by perliedman** [comment] 2017-11-23 07:36
Hi, yeah that looks more or less ok. Have you checked dev tools for errors? Just adding try-catches and alerts will not give you asynchronous errors. I bet there is something going on there.

I made a running example using the code you pasted above (but with another URL): https://plnkr.co/edit/tk0dYpZmR7mjKiclpLsa?p=preview - as you can see, it works as expected (I think), so I think there must be some detail on your end that explains the problem.

**Comment by sfindlay** [comment] 2017-11-23 16:05
Okay must be an issue with the libraries I have installed, I downloaded the latest version of leaflet and obtained your version from the link a couple days ago. Do you know how I could check the versions easy? I will check the dev tools as well…

Steven Findlay

CEO
Noratek Solutions, Inc
Work:  (250) 564-2236 | Cell:  (250) 981-3025
sfindlay@noratek.com<mailto:sfindlay@noratek.com>
http://www.noratek.com/ | https://www.cityinspectionsoftware.com<https://www.cityinspectionsoftware.com/>

Noratek Solutions 200-1840 3rd Avenue Prince George, BC V2M 1G4 Canada

**Comment by sfindlay** [comment] 2017-11-23 18:39
I’m getting the following error:

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data undefined  leaflet-realtime.js:233:13

However my web service never gets called?

Steven Findlay

CEO
Noratek Solutions, Inc
Work:  (250) 564-2236 | Cell:  (250) 981-3025
sfindlay@noratek.com<mailto:sfindlay@noratek.com>
http://www.noratek.com/ | https://www.cityinspectionsoftware.com<https://www.cityinspectionsoftware.com/>

Noratek Solutions 200-1840 3rd Avenue Prince George, BC V2M 1G4 Canada

**Comment by sfindlay** [comment] 2017-11-23 18:58
I have cut the code down to:

try {
    realtimeLayer = L.realtime({
        url: 'http://localhost:8080/cityReporter/Mapping/devicePositionsFiltered',
        crossOrigin: true
    }, {
        start: 'True',
        interval: 20000
    }).addTo(map);
}
catch (err) {
    alert('Error: '||err.message)
}

And I have the following output in the developer console on Firefox:

[cid:image001.png@01D36449.F1F56DA0]

I have placed a break point on my web service and I can tell it never gets called, not sure why but it would appear everything should be fine….

Steven Findlay

CEO
Noratek Solutions, Inc
Work:  (250) 564-2236 | Cell:  (250) 981-3025
sfindlay@noratek.com<mailto:sfindlay@noratek.com>
http://www.noratek.com/ | https://www.cityinspectionsoftware.com<https://www.cityinspectionsoftware.com/>

Noratek Solutions 200-1840 3rd Avenue Prince George, BC V2M 1G4 Canada

**Comment by perliedman** [comment] 2017-11-24 08:55
The syntax error means that the response from your service can't be parsed as JSON. Check that it's actually calling the correct URL and that the response is as expected. You can use the Network tab in your browser's dev tools to do this.

I'm going to close this, since it doesn't look likely that this is an issue with Leaflet Realtime. Please add more information if you think this is an issue in Leaflet Realtime and not in your setup, and I'll consider re-opening.

**Closed by perliedman** 2017-11-24 08:55 UTC

**Comment by sfindlay** [comment] 2017-11-24 18:53
Perhaps you missed my one email, the leaflet-realtime never calls my web service, I have a break point on the web service to verify it doesn’t get called. I have another piece of code as shown below and it works without error???


$.getJSON(' http://localhost:8080/cityReporter/Mapping/devicePositionsFiltered?startDate='+startDateTime+
        '&endDate='+endDateTime+'&areaid='+fvAreaIdSelected+'&formgroupid='+fvFormgroupIdSelected+
        '&formid='+fvFormIdSelected+'&includeDetails='+fvIncludeDetails, function (data) {
    // add GeoJSON layer to the map once the file is loaded
    if (refreshMap && myLayer) {
        myLayer.clearLayers();
    }

    myLayer = L.geoJSON(data, {
        onEachFeature: function (feature, layer) {
            layer.bindPopup('<h1>' + feature.properties.name + '</h1><p>' + feature.properties.popupContent + '</p>');
        }
    }).addTo(map);

    myLayer.setStyle({color: 'green', weight: 5, opacity: 1, bold: true});

    map.spin(false);
})
.error(function() { map.spin(false);});


Steven Findlay

CEO
Noratek Solutions, Inc
Work:  (250) 564-2236 | Cell:  (250) 981-3025
sfindlay@noratek.com<mailto:sfindlay@noratek.com>
http://www.noratek.com/ | https://www.cityinspectionsoftware.com<https://www.cityinspectionsoftware.com/>

Noratek Solutions 200-1840 3rd Avenue Prince George, BC V2M 1G4 Canada

**Comment by perliedman** [comment] 2017-11-26 10:34
Perhaps it's calling another web service than you think?

Check dev tools network tab and see what request is actually being made, and what the response is. Another option is to set a breakpoint on line 233 in Leaflet Realtime (where the error happens, according to the stack trace you pasted above), and see what data it's trying to parse; you should be able to figure out what the problem is from there.
